//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWColorizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWColorizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;codeColors&gt;
        ///	&lt;colorGroup&gt;
        ///		&lt;syntaxColor id=&quot;CodeColor_HTMLEntity&quot; bold=&quot;true&quot; /&gt;
        ///		&lt;syntaxColor id=&quot;CodeColor_JavascriptNative&quot; text=&quot;#009999&quot; /&gt;
        ///		&lt;syntaxColor id=&quot;CodeColor_JavascriptNumber&quot; text=&quot;#FF0000&quot; /&gt;
        ///		&lt;syntaxColor id=&quot;CodeColor_JavascriptClient&quot; text=&quot;#990099&quot; /&gt;
        ///		&lt;syntaxColor id=&quot;CodeColor_JavascriptSpryKeywords&quot; text=&quot;#FF6208&quot; /&gt;
        ///		&lt;syntaxColor id=&quot;CodeColor_JavascriptSpryClasses&quot; text=&quot;#FF6208&quot; /&gt;
        ///		&lt;syntaxColor id=&quot;CodeColor_TemplateText&quot; text=&quot;#999999&quot; /&gt;
        ///		&lt;syntaxColor id=&quot;Code [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
    }
}
